### ISSUE TITLE
VideoFilterVC2: Video gets pixelated in iOS 13

### ISSUE THREAD

**Issue by heythiswildidea** [Silence-GitHub/BBMetalImage#18]
When you filter the video in VideoFilterVC2.swift with iPhone 11 (iOS 13), the video falters during playback and becomes partially pixelated. Everything works fine on an iPhone 6 (iOS 12.1).
I used the current demo version for this test.

**Comment by Silence-GitHub** [comment]
Is there any log in the console for iPhone 11 (iOS 13)?

**Comment by heythiswildidea** [comment]
The console displays the error "Asset writer or video input is not ready for writing this frame" several times.
Here I uploaded a screen recording of the error as GIF: http://gifsstore.com/public/upload/gifs/15691318361569131822.gif

**Comment by Silence-GitHub** [comment]
Try to sleep some time in the video source progress callback. If there is still the same error ("Asset writer or video input is not ready for writing this frame"), try to sleep for a longer duration.

```
videoSource.start(progress: { (_) in
    usleep(5 * 1000)
}) { (_) in
    // Completion
}
```

**Comment by heythiswildidea** [comment]
That worked. The error no longer occurs. Thank you very much for your help.

**Comment by Silence-GitHub** [comment]
I guess the reason of the error is that, GPU is much faster than CPU for some iPhones. So the video writer gets too many frames to write. Some frames are dropped because video writer is not ready to write. If I don't drop the video frames, there may be memory issue. Sleeping to wait is the solution. You can test different devices to determine the sleep duration.
